defaults: defaults.yaml

case_name: candidate_gen8

materials:
  substrate: Si
  film: ZnSe
  structure: ZnSe

geometry:
  period_um: [2.8, 2.8]
  pillar_side_um: 1.529878280548516
  pillar_thickness_um: 1.1985267927264762
  film_thickness_um: 0.9385750535924566
  substrate_thickness_um: 5.0

output:
  run_dir: outputs/fdtd/candidate_gen8
